version: '3.3'
services:

  api:
    build:
      context: ../ign-portfolio-backend
    volumes:
      - ../ign-portfolio-backend:/usr/src/app
    ports:
      - '3000:3000'
    expose:
      - '3000'
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql

  migration:
    image: ign-portfolio-backend_api:latest
    volumes:
      - ../ign-portfolio-backend:/usr/src/app
    command: >
      bash -c "bash .wait-for-it.sh mysql:3306 -- npm run migrate"

    links:
      - mysql
    depends_on:
      - mysql

volumes:
  my-db:
